name = "RowBinaryFiles"
uuid = "477270c0-3eeb-11e9-1df9-e50cde4ac4a6"
authors = ["Ciarán O'Mara <Ciaran.OMara@utas.edu.au>"]
version = "0.1.0"

[deps]
BufferedStreams = "e1450e63-4bb3-523b-b2a4-4ffa8c0fd77d"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
